### ISSUE TITLE
Вынеси компоненты Header и Footer за роутер, что-бы они не перерисововались  

### ISSUE THREAD

**Issue by scandy5** [Ihor92/App-Uber-Eats#7]
![image](https://user-images.githubusercontent.com/41551315/61174951-24b24200-a5b0-11e9-8dbc-5ea0eb3134eb.png)

**Comment by Ihor92** [comment]
Header и Footer находиться в Router потому, что в этих элементах есть Link на logo. При нажатии на logo происходит переход на главную страницу.
